#+begin_html
---
title: Research
tags:
---
#+end_html

#+BEGIN_HTML
  <h2 class="ui header">Research</h2>
#+END_HTML

I'm a [[http://people.cecs.anu.edu.au/user/4919][Research Fellow]] in the School of Computer Science at
the Australian National University, working under Prof. John Hosking
and Assoc. Prof. Henry Gardner.

My primary research interest these days is *livecoding*, and I'm
currently working on [[https://github.com/digego/extempore][Extempore]] (as you may have been able
to guess from the content of [[../latest-posts/index.html][this blog]]). Before Extempore came along I
was an [[http://impromptu.moso.com.au][Impromptu]] user, and have been live coding since 2007. You can
check out some of my screencasts [[http://vimeo.com/benswift/videos][on vimeo]].

I have a PhD in Computer Science from the Australian National
University. My research project was a cross-disciplinary project
between computer science and digital media ([[http://dl.dropbox.com/u/18333720/master.pdf][thesis]]). Prior to that I
did a BSc (Hons) in Mathematics at the ANU.

If you want to get in touch, email is best---you can reach me on
[[mailto:ben@benswift.me][ben@benswift.me]].

* Potential students

If you're interested in doing research with me, particularly in
livecoding with Extempore, then [[mailto:ben@benswift.me][get in touch]]. If you can, send me a
link to something you've made: a livecoding video, a project on
GitHub, or something like that.

* Publications

- Arrian Purcell, Henry Gardner and *Ben Swift* “Visualising a Live
  Coding Arts Process” In Proceedings of the 26th Conference of the
  Computer-Human Interaction Special Interest Group of Australia on
  Computer-Human Interaction, OZCHI ’14.
- Duan, Xiaojuan, Jianping Wu, *Benjamin Swift*, and Thomas Brett
  Kirk. “Texture Analysis of the 3D Collagen Network and Automatic
  Classification of the Physiology of Articular Cartilage.” Computer
  Methods in Biomechanics and Biomedical Engineering, January 16,
  2014, 1–13. doi:10.1080/10255842.2013.864284.
- Martin, Charles, Henry Gardner, and *Ben Swift*. “Exploring
  Percussive Gesture on iPads with Ensemble Metatone.” In Proceedings
  of the SIGCHI Conference on Human Factors in Computing Systems,
  1025–28. CHI ’14. New York, NY, USA: ACM, 2014.
  doi:10.1145/2556288.2557226.
- Martin, Charles, Henry Gardner, and *Ben Swift*. “Metatravels and
  Metalonsdale: Ipad Apps for Percussive Improvisation.” In CHI ’14
  Extended Abstracts on Human Factors in Computing Systems, 547–50.
  CHI EA ’14. New York, NY, USA: ACM, 2014.
  doi:10.1145/2559206.2574805.
- Sorensen, Andrew, *Ben Swift*, and Alistair Riddell. “The Many
  Meanings of Live Coding.” Computer Music Journal 38, no. 1 (2014):
  65–76.
- *Swift, Ben*. “Chasing a Feeling: Experience in Computer Supported
  Jamming.” In Music and Human-Computer Interaction, edited by Simon
  Holland, Katie Wilkie, Paul Mulholland, and Allan Seago, 85–99.
  Springer Series on Cultural Computing. Springer London, 2013.
  http://link.springer.com/chapter/10.1007/978-1-4471-2990-5_5.
- *Swift, Ben*, Henry J Gardner, and Alistair Riddell. “A Chasing
  After the Wind: Experience in Computer-Supported Group
  Music-Making.” In When Words Fail: What Can Music Interaction Tell
  Us about HCI? Workshop at BCS HCI 2011, 2011.
  http://mcl.open.ac.uk/Workshop/uploads/xambo_BHCI-2011-position-paper-CR-final.pdf.
- *Swift, Ben*, Henry J Gardner, and Alistair Riddell. “Distributed
  Performance in Live Coding.” In ACMC ’09: Proceedings of the
  Australasian Computer Music Conference, 2009.
- *Swift, Ben*, Henry Gardner, and Alistair Riddell. “Engagement
  Networks in Social Music-Making.” In Proceedings of the 22nd
  Conference of the Computer-Human Interaction Special Interest Group
  of Australia on Computer-Human Interaction, 104–11. OZCHI ’10. New
  York, NY, USA: ACM, 2010. doi:10.1145/1952222.1952244.
- *Swift, Ben*jamin. “Becoming-Sound: Affect and Assemblage in
  Improvisational Digital Music Making.” In Proceedings of the SIGCHI
  Conference on Human Factors in Computing Systems, 1815–24. CHI ’12.
  New York, NY, USA: ACM, 2012. doi:10.1145/2207676.2208315.
- *Swift, Ben*, James Sheridan, Yang Zhen, and Henry J. Gardner.
  “Mind-Modulated Music in the Mind Attention Interface.” In
  Proceedings of the 19th Australasian Conference on Computer-Human
  Interaction: Entertaining User Interfaces, 83–86. OZCHI ’07. New
  York, NY, USA: ACM, 2007. doi:10.1145/1324892.1324907.
- *Swift, Ben*, Andrew Sorensen, Henry J Gardner, and J Hosking.
  “Visual Code Annotations for Cyberphysical Programming.” In Live
  ’13: Workshop on Live Programming at ICSE ’13, 2013.
- *Swift, Ben*, Andrew Sorensen, Michael Martin, and Henry Gardner.
  “Coding Livecoding.” In Proceedings of the 32Nd Annual ACM
  Conference on Human Factors in Computing Systems, 1021–24. CHI ’14.
  New York, NY, USA: ACM, 2014. doi:10.1145/2556288.2557049.

If you have trouble tracking any of these down, [[mailto:ben@benswift.me][send me an email]] and I
can rustle you up a pre-print.

* Curated Artistic Performances

- *Swift, Ben* (2014). In: "/You Are Here/" /Arts Festival/. April 2014,
  Canberra, Australia. Curator: Tom Swann.
- *Swift, Ben* and Torben Sko (2014). In: "/Art, Not Apart/" /Festival/.
  April 2014, Canberra, Australia. Curator: David Caffery.
- *Swift, Ben* and Andrew Sorensen (2013). In: /MUME '13: Musical
  Metacreation Weekend/ at ISEA 2013: International Symposium on
  Electronic Art. June 2013, Sydney, Australia. Curator: Oliver Bown.
- *Swift, Ben* (2013). In: /Revenant Media: Theremin '75 Exhibition/,
  ANU School of Art. October 2013, Canberra, Australia. Curator:
  Martin Jolly.
- *Swift, Ben* (2010). In: "/Beginning, Middle, End/" /Festival/, ANU
  School of Art. September 2010, Canberra, Australia. Curator: Martin
  Jolly.
- *Swift, Ben* (2009). In: /Australasian Computer Music Conference/.
  June 2009, Brisbane, Australia.
- *Swift, Ben* (2008). In: "/Transmissions in Sound/" /Festival/, ANU
  School of Art. October 2008, Canberra, Australia.

* Invited Talks

- *Swift, Ben* "Livecoding Physics Simulation as Performance",
  /Invited presentation at the 2014 Australian Institute of Physics
  Congress/ http://www.aip2014.org.au/
- *Swift, Ben* and Andrew Sorensen (2013). "Live Coding Live". In:
  /IEEE Symposium on Visual Languages and Human-Centric Computing. San
  Jose, USA/
- *Swift, Ben* (2010). "Livecoding in Impromptu". /Invited
  presentation at National University of Singapore/ 12 July 2000

# - *A Sorensen, B Swift, A Riddell* (2014, to appear). The Many Meanings
#   of Live Coding. /Computer Music Journal 38:1/
# - *B Swift, A Sorensen, M Martin, H Gardner* (2014, to appear). Coding
#   Livecoding. /CHI '14: Proceedings of the International Conference on
#   Human Factors in Computing Systems./
# - *X Duan, J Wu, B Swift, and TB Kirk* (2014). Texture analysis of the
#   3D collagen network and automatic classification of the physiology
#   of articular cartilage. /Computer Methods in Biomechanics and
#   Biomedical Engineering/
# - *B Swift, A Sorensen, H Gardner, J Hosking* (2013). Visual Code
#   Annotations for Cyberphysical Programming. /LIVE '13: Workshop on
#   Live Programming at ICSE '13/
# - *B Swift* (2012). Becoming Sound: Affect and Assemblage in
#   Improvisational Digital Music-Making. /CHI '12: Proceedings of the
#   International Conference on Human Factors in Computing Systems./
# - *B Swift* (2012). Chasing a Feeling: Experience in
#   Computer Supported Jamming. /Music and Human-Computer Interaction./
#   Springer.
# - *B Swift* (2011) Impish Grooves. /2011 Computer Music Journal DVD/
# - *B Swift, H Gardner, A Riddell* (2011). A Chasing After the Wind:
#   Experience in Computer-Supported Group Music-Making. /When Words
#   Fail: What can music interaction tell us about HCI? Workshop at BCS HCI 2011./
# - *B Swift, H Gardner, A Riddell* (2010). Engagement Networks in Social
#   Music-making. /OZCHI '10: Proceedings of the Australasian
#   Conference on Computer-Human Interaction./
# - *B Swift, H Gardner, A Riddell* (2009). Distributed Performance in
#   Live Coding. /ACMC '09: Proceedings of the Australasian Computer
#   Music Conference./
# - *B Swift, H Gardner, A Riddell* (2007). Mind-modulated music in the
#   mind attention interface. /OZCHI '07: Proceedings of the
#   Australasian Conference on Computer-Human Interaction./

# I live mainly in the world of Human-Computer Interaction (HCI),
# although I also have a digital artist (Dr. Alistair Riddell) and a
# geographer (Dr. David Bissell) on my panel. I'm interested in group
# musical collaboration, and specifically the patterns of engagement
# between musicians in that context. I've built an iOS-based group
# jamming system called Viscotheque, and I've been using it to jam
# around with some musicians from around campus. If you'd like to get
# involved, [[mailto:ben@benswift.me][drop me a line]].

# I'm also interested in critically examining the logical-positivist
# underpinnings of HCI theory and practice, especially when it comes to
# computers and group musical creativity. I'm encouraged by recent
# critiques and proposed alternative foundations, such as Dourish's
# /embodied computing/, McCarthy and Wright's /technology as experience/
# and Bardzell's /interaction criticism/. I've increasingly found myself
# thinking in those (and related) spaces as I try to understand the use
# of computing devices in open-ended group interaction.

# * Publications

# - *B Swift* (2012). Becoming Sound: Affect and
# Assemblage in Improvisational Digital Music-Making. /CHI '12:
# Proceedings of the International Conference on Human Factors in
# Computing Systems./
# - *B Swift* (2012). Chasing a Feeling: Experience in
# Computer Supported Jamming. /Music and Human-Computer Interaction./
# Springer.
# - *B Swift* (2011) Impish Grooves. /2011 Computer Music Journal DVD/
# - *B Swift, H Gardner, A Riddell* (2011). A Chasing After the Wind:
# Experience in Computer-Supported Group Music-Making. /When Words
# Fail: What can music interaction tell us about HCI? Workshop at BCS
# HCI 2011./
# - *B Swift, H Gardner, A Riddell* (2010). Engagement Networks in Social
# Music-making. /OZCHI '10: Proceedings of the Australasian
# Conference on Computer-Human Interaction./
# - *B Swift, H Gardner, A Riddell* (2009). Distributed Performance in
# Live Coding. /ACMC '09: Proceedings of the Australasian Computer Music
# Conference./
# - *B Swift, H Gardner, A Riddell* (2007). Mind-modulated music in the
# mind attention interface. /OZCHI '07: Proceedings of the Australasian
# Conference on Computer-Human Interaction./

# [fn:postdoc] I'm technically not a post-doc /yet/---I submitted a few
# months ago but I'm still waiting to hear back. But I'm working as a
# post-doc, anyway.
