#+begin_html
---
layout: post
title: "Building Extempore on OSX & Linux"
date: 2012-11-06 18:50
comments: true
categories:
---
#+end_html

On OSX and Linux, Extempore has three main dependencies:

- =LLVM v3.0=
- =pcre=
- =portaudio v1.9=

The one tricky dependency is LLVM v3.0, which requires a patch (see
instructions in the next section). If you have any problems with these
versions (or success with newer/older versions) then feel free to let
me know on the [[mailto:extemporelang@googlegroups.com][Extempore mailing list]].

*Linux*

On a fresh Ubuntu 12.10, I needed the following packages (available
through =apt-get= or =aptitude=)

- =clang= (for compiling LLVM)
- =g++= (for compiling Extempore)
- =portaudio19-dev=
- =libpcre3-dev=
- =libgl1-mesa-dev= (OpenGL)

*OSX*

The easiest way to get the dependencies is through a package manager.
I use [[http://mxcl.github.com/homebrew/][Homebrew]], [fn:alternatives] which uses the [[https://developer.apple.com/downloads/index.action?%3Dcommand%2520line%2520tools][OSX command line
tools]]. With Homebrew, installing the dependencies is as simple as

#+begin_src sh
brew install pcre portaudio
#+end_src

* Building LLVM v3.0

LLVM *must* be version 3.0 and needs to be built from source, because
a small patch to =LLParser.cpp= (an LLVM source file) is required. The
patch file =llparser.patch= is supplied in the =extempore/extras=
directory. You can get the LLVM 3.0 source [[http://llvm.org/releases/download.html#3.0][here]].

To apply the patch just move into  =llvm/lib/AsmParser= directory and
then apply the =llparser.patch= file which in can be found in
=extempore/extras=, e.g.

#+begin_src sh
$ cd /path/to/llvm/lib/AsmParser
$ patch < /path/to/extempore/extras/llparser.patch
#+end_src

After that, building LLVM is the usual =./configure; make; make
install= process, with the addition of a =--prefix= location
specifying where everything will be installed into (such as a =build=
directory)

#+begin_src sh
$ cd /path/to/llvm
$ mkdir build
$ ./configure --prefix=/path/to/llvm/build --enable-optimized
$ make && make install
#+end_src

/A note on compiling LLVM with Clang/LLVM-gcc/ 

There is a bug in the LLVM v3.0 source code which means that LLVM
won't compile versions of Clang newer than clang v3.0, instead giving
the error: 

#+begin_src compilation
IntervalMap.h:1980:32: error: use 'template' keyword to treat 'newNode' as a dependent template name
#+end_src

To fix this,[fn:jleonard] you'll need to add in a missing =template=
keyword in =include/llvm/ADT/IntervalMap.h=. Change line 1980 to

#+begin_src cpp
Node[NewNode] = this->map->template newNode<NodeT>();
#+end_src

A longer-term fix to this problem is that LLVM 3.2 is scheduled for
release in mid-December, and when that happens we'll update Extempore
to use this version of LLVM (in which the above bug is fixed). This
will be good news all round, but it's probably a couple of months
away, so thanks for your patience!

* Building Extempore

Now that all of the dependencies have been built, we can compile
Extempore. First, let Extempore know where the LLVM build
directory[fn:builddir] is by defining the shell variable
=EXT_LLVM_DIR=, for example

#+begin_src sh
$ export EXT_LLVM_DIR=/path/to/llvm/Build
#+end_src

Then you can build Extempore using the =all.bash= shell script 

#+begin_src sh
$ ./all.bash
#+end_src

...and you should have a shiny new =extempore= executable in your
directory to play with.

* Ok, so how do I start using Extempore?

The =extempore= executable on its own is cool, but things really start
to get interesting when you can interact with it by sending it xtlang
code to evaluate. So the next step is to [[file:2012-09-26-interacting-with-the-extempore-compiler.org][set up your text editor for
working with Extempore source code]].

After you're set up, then the next step is to learn about xtlang and
the Extempore runtime. The [[file:../extempore-docs/index.org][docs index]] has a complete list of all the
posts covering this stuff, and is probably the place to go next. Have
fun :)

[fn:alternatives] If you have a preferred package manager (Fink or
Macports) or even want to build them yourself, then you can do it that
way too.

[fn:builddir] i.e. the directory we specified with the =--prefix=
argument to the LLVM =./configure= script.

[fn:jleonard] Thanks to Jonathan Leonard for suggesting the fix.
