#+begin_html
---
layout: post
title: "Building Extempore on OSX & Linux"
date: 2012-11-06 18:50
comments: true
categories:
---
#+end_html

Extempore has four static dependencies:

- =LLVM v3.0=
- =pthread=
- =pcre= (Perl-compatible Regular Expressions)
- =portaudio v1.9=

You need to download and build these packages before Extempore will
compile.  Some of the dependencies listed have specific versions,
while for others the latest version should be fine.  If you have any
problems with these versions (or success with newer/older versions)
then feel free to let me know on the [[mailto:extemporelang@googlegroups.com][Extempore mailing list]].

*Linux*

If you're on Linux, you probably already know what you're doing when
building things from source. The dependencies are all available
through =apt-get= on Ubuntu, although you may need to install the
'dev' versions to make sure you download the headers as well. The one
exception is LLVM, which has to be patched and compiled manually (see
instructions in the next section).

*OSX*

The easiest way to get the Extempore dependencies is through a package
manager. I use [[http://mxcl.github.com/homebrew/][Homebrew]], [fn:alternatives] which uses the [[https://developer.apple.com/downloads/index.action?%3Dcommand%2520line%2520tools][OSX command
line tools]]. With Homebrew, installing the dependencies is as simple as

#+begin_src sh
brew install pthread prcre portaudio
#+end_src

As in the Linux case, the exception is LLVM v3.0, which must be
patched and built manually.

* Building LLVM v3.0

LLVM *must* be version 3.0 and needs to be built from source, because
a small patch to =LLParser.cpp= (an LLVM source file) is required. The
patch file =llparser.patch= is supplied in the =extempore/extras=
directory. You can get the LLVM 3.0 source [[http://llvm.org/releases/download.html#3.0][here]].

To apply the patch just move into  =llvm/lib/AsmParser= directory and
then apply the =llparser.patch= file which in can be found in
=extempore/extras=, e.g.

#+begin_src sh
$ cd /path/to/llvm/lib/AsmParser
$ patch < /path/to/extempore/extras/llparser.patch
#+end_src

After that, building LLVM is the usual =./configure; make; make
install= process, with the addition of a =--prefix= location
specifying where everything will be installed into (such as a =Build=
directory)

#+begin_src sh
$ cd /path/to/llvm
$ mkdir Build
$ ./configure --prefix=/path/to/llvm/Build --enable-optimized
$ make -j4
$ make install
#+end_src

/OSX users: if you have problems with an error in/ =IntervalMap.h=
/then try updating to the latest version of the OSX command line
tools/

* Building Extempore

Now that all of the dependencies have been built, we can compile
Extempore. First, let Extempore know where the LLVM build
directory[fn:builddir] is by defining the shell variable
=EXT_LLVM_DIR=, for example

#+begin_src sh
$ export EXT_LLVM_DIR=/path/to/llvm/Build
#+end_src

Then you can build Extempore using the =all.bash= shell script 

#+begin_src sh
$ ./all.bash
#+end_src

...and you should have a shiny new =extempore= executable in your
directory to play with.

* Ok, so how do I start using Extempore?

The =extempore= executable on its own is cool, but things really start
to get interesting when you can interact with it by sending it xtlang
code to evaluate. So the next step is to [[file:2012-09-26-interacting-with-the-extempore-compiler.org][set up your text editor for
working with Extempore source code]].

After you're set up, then the next step is to learn about xtlang and
the Extempore runtime. The [[file:../extempore-docs/index.org][docs index]] has a complete list of all the
posts covering this stuff, and is probably the place to go next. Have
fun :)

[fn:alternatives] If you have a preferred package manager (Fink or
Macports) or even want to build them yourself, then feel free to do
that also.

[fn:builddir] i.e. the directory we specified with the =--prefix=
argument to the LLVM =./configure= script.
