#+begin_html
---
layout: post
title: "Downloading and installing Extempore"
date: 2012-10-30 11:33
comments: true
categories:
---
#+end_html

*Update 2013-9-25: Binaries are currently unavailable: we're hoping to have them back real soon.  In the meantime, instructions on how to build from source on [[file:2013-03-20-building-extempore-on-osx-linux.org][OSX/Linux]] or [[file:2013-03-20-building-extempore-on-windows.org][Windows]].*

The easiest way to get up and running with Extempore is to download a
binary tarball. A binary is an [[http://en.wikipedia.org/wiki/Executable][executable]] which someone has already
compiled for your platform (operating system & architecture), so you
can just copy it into place and run it.

* Downloading a pre-compiled Extempore

Extempore binary downloads are available for these platforms:

# /Note: these binaries are changing pretty frequently at the moment as we nail down the xtlang standard library.  So if something is broken in any of the examples, let us know on the mailing list./

- OSX (built on 10.8) /temporarily unavailable/
- Linux (built on Ubuntu 13.04) /temporarily unavailable/
- Windows 7/8 (64bit) /not yet available/

So, to download: click on the link corresponding to the OS you're on,
and pull down the latest tar.gz file. You can tell which one is the
latest from the date in the filename, e.g.
=extempore-Darwin-2013.07.11.tar.gz= was built on 7 July 2013.

The OSX and Linux binaries are built (and tested) on 10.8 and Ubuntu
13.04 respectively. They may well work on older versions (and other
Linux distros), but even if they don't you can still [[file:2013-03-20-building-extempore-on-osx-linux.org][build from
source]]. Also, there's no Windows binary download at the
moment,[fn::Although we are taking enquiries for the job of a Windows
binary maintainer :)] so if you're on Windows you'll have to [[file:2013-03-20-building-extempore-on-windows.org][build
from source]] as well.

* 'Installing' a pre-compiled Extempore

Installation is as simple as unpacking the tarball and (optionally)
moving the =extempore= directory wherever you'd like (I keep it in
=~/Code= myself). Everything Extempore needs is in there---it's
self-contained, so downloading the tarball makes installation
essentially a one-step process. For example, if the tar file was
called =extempore-Darwin-2013.07.11.tar.gz=, you can unpack it with

#+BEGIN_SRC sh
tar xf extempore-Darwin-2013.07.11.tar.gz
# you can get rid of the tarball now, just to minimise clutter
rm extempore-Darwin-2013.07.11.tar.gz
#+END_SRC

After that's done, =cd= into the =extempore= directory, [[file:2012-09-26-interacting-with-the-extempore-compiler.org][fire up a
command prompt]] and start extempore running.

There's lots more to be said here, particularly if you're just
starting out with Extempore.  Head over to the [[file:../extempore-docs/index.org][main docs]] and see what
takes your fancy.
