#+begin_html
---
layout: post
title: "Extempore & Sublime Text 2 cheat sheet"
date: 2012-23-10 13:46
comments: true
categories:
---
#+end_html

[[http://www.sublimetext.com][Sublime Text 2]] (ST2) is a cross-platform text editor which runs on OS
X, Linux and Windows. It's the 'spiritual successor' to Textmate, and
it has some cool features, a large variety of plugins for different
languages and tasks, and a great community.

I won't cover all the basics of ST2 here, because the [[http://docs.sublimetext.info/en/latest/][(unofficial)
documentation]] does that pretty well. Think of this post as more as a
'cheat sheet', for dipping back into to refresh your memory when you
just can't remember how to do something off the top of your head.

* Installing ST2

Installing ST2 is a piece of cake---there are binaries for all
platforms on the [[http://www.sublimetext.com/2][download]] page.

You'll also need the [[https://github.com/mlozanov/extempore-sublime][ST2 Extempore plugin]], which provides syntax
highlighting and some commands for connecting to and working with a
running Extempore process. To install the plugin, download the [[https://github.com/mlozanov/extempore-sublime/zipball/master][plugin
files]] (or clone the repo) and unzip them into your [[http://docs.sublimetext.info/en/latest/basic_concepts.html#the-packages-directory][ST2 packages
directory]].

* Hacking on Extempore code in ST2

These are the steps youll need to take to start hacking on a piece of
Extempore code in Emacs:

1. start ST2
2. open up your favourite shell (e.g. Terminal on OS X or cmd.exe on
   Windows)
3. =cd= into your Extempore directory and run =extempore=, e.g.
   =./extempore --device 2=
4. open up an ST2 buffer with an Extempore file (the Extempore plugin
   should be loaded automatically when ST2 sees the =.xtm= file
   extension)
5. connect to the running Extempore process (=Tools > Extempore > Connect=)

Then, to [[file:2012-09-26-interacting-with-the-extempore-compiler.org][evaluate]] Extempore code, highlight the code you want to
evaluate and hit =evaluate region=, which by default is mapped to
=ctrl+r=

To restart the Extempore process, just =ctrl+c= in the shell where
=extempore= is running to kill it, then start it up again.

* Known issues with the Extempore ST2 plugin

The syntax highlighting currently doesn't cover a few edge cases---so
if you end up tinkering with =Extempore.JSON-tmLanguage= to fix
anything then feel free to submit a patch.

Also, =extempore_evaluate= currently requires *highlighting* the code
to evaluate. It would be nice if it would eval the top-level
s-expression if no region was highlighted. This is hopefully trivial
to add if you know a bit about how ST2 works.
