#+begin_html
---
layout: post
title: "Downloading and installing Extempore"
date: 2012-10-30 11:33
comments: true
categories:
---
#+end_html

The easiest way to get up and running with Extempore is to download a
binary version. A binary is an [[http://en.wikipedia.org/wiki/Executable][executable]] which someone has already
compiled for your platform (operating system & architecture), so you
can just copy it into place and run it.

To run, the Extempore requires the =extempore= executable and the
=runtime= directory which is loaded when the executable starts
up.[fn:startup] The executable provides the basic runtime environment
(including todo the scheduler) while the =.xtm= files in =runtime=
provide some other necessary infrastructure (including the xtlang
compiler).[fn:runtime-flag]

So, at the very minimum, you'll need an extempore directory which
looks like this:

#+begin_example
.
|-- extempore
`-- runtime
    |-- code.ir
    |-- init.xtm
    |-- llvmir.xtm
    |-- llvmti.xtm
    `-- scheme.xtm
#+end_example

* Downloading and 'Installing' the Extempore zip file

There are three steps:

1. get the binary
2. get the Extempore source
3. copy the binary into the source directory

*Getting the binary*

Extempore binary downloads are available from Extempore's [[https://github.com/digego/extempore/downloads][downloads]]
page on GitHub for these platforms:

- OSX
- Ubuntu
- Windows 7/8 (64bit) (/coming soon/)

*Getting the Extempore source*

These downloads don't contain the =runtime= directory which Extempore
needs to run (or any of the other libraries, or example files, etc).
You need to get these files separately from the Extempore GitHub page.

If you don't care about staying up-to-date with the latest
development, then you can get a zip file of the latest =master= branch
[[https://github.com/digego/extempore/archive/master.zip][here]]. If you'd like to stay up-to-date, clone the Extempore git
repository: open up a shell, =cd= to the directory you want to keep
the Extempore source code in and type

#+begin_src sh
git clone https://github.com/digego/extempore.git
#+end_src

If your system doesn't have git installed, [[http://git-scm.com/downloads][here are some instructions]]
on how to get it.

*Copying the binary into the source directory*

'Installing' Extempore really just means moving the =extempore=
executable into the source directory you just downloaded. You can put
the source directory wherever you like. If you have a place that you
put that sort of thing (e.g. in a =Code= folder in your home
directory) you can put it there---it doesn't matter. As long as the
=extempore= executable is in the top level and the =runtime= directory
exists, then you can [[file:2012-09-26-interacting-with-the-extempore-compiler.org][fire up a command prompt]] and start Extempore
running.

There's lots more to be said here, particularly if you're just
starting out with Extempore.  Head over to the [[file:../extempore-docs/index.org][main docs]] and see what
takes your fancy.

[fn:startup] [[file:2012-09-26-interacting-with-the-extempore-compiler.org][This post]] shows how to start up and interact with the
=extempore= executable.

[fn:runtime-flag] If for some reason you need to have the =extempore=
and the =runtime= directory in different places, you can specify the
path to the =runtime= directory by using the =--runtime= command line
option when starting =extempore=.
