#+begin_html
---
layout: post
title: "Extempore binary: beta testers wanted"
date: 2013-10-15 17:49
comments: true
categories:
---
#+end_html

Hey folks

Some good news from Extempore-land: we've got some Extempore binaries
for OSX and Linux. This should make it a lot easier to get up and
running with Extempore---just download a tarball/zipfile, unpack it
and away you go. Some of you may have been waiting for ages for these
binaries, so thanks for your patience.

What we really need right now is some beta-testers for these binaries.
It's tricky to build a binary (and all the necessary shared libs,
which are included in the tarball) which will work on all the
different versions of OSX and various flavours which are out there. We
think these ones work, but we need your help to iron out all the rough
edges.

So, if you're on OSX or Linux, it would be great if you could help us
out by:

1. grabbing the binary archive from the server ([[http://extempore.moso.com.au/extras/extempore_osx_20131012.tgz][OSX]], [[http://extempore.moso.com.au/extras/extempore_linux_20131012.tgz][Linux]])
2. unpacking it somewhere
3. in the top-level =extempore= directory, run these example files and
   let us know if they work

#+BEGIN_SRC sh
# move into the extempore directory
> cd extempore

# this example should play some audio (a little synth pattern)
# don't worry about the stutter in the audio at the beginning
> ./extempore --run examples/core/polysynth.xtm

# this example should open up a 3D graphics scene
> ./extempore --run examples/external/xtmrender2.xtm
#+END_SRC

If you hear some audio (for the =polysynth.xtm= example) and see a 3D
scene rendered (for =xtmrender2.xtm=) then your're golden. Let us know
on the [[mailto:extemporelang@googlegroups.com][mailing list]] (including which OS version/distro you're
running).

If Extempore crashes, then it would be great if you could [[mailto:extemporelang@googlegroups.com][let us know]]
about that too, including any details you can give about what went
wrong.

So far, we're reasonably confident about

- *OSX* 10.7+ (and possibly 10.6)
- *Ubuntu* 12.10, 13.04

If you're on another distros/versions we're keen to hear from you.

Thanks in advance :)
