#+PROPERTY: header-args:extempore :tangle /tmp/2013-03-20-building-extempore-on-osx-linux.xtm
#+begin_html
---
title: Building Extempore from source on OSX & Linux
alias: ["./2013-03-20-building-extempore-on-osx-linux.html"]
tags: setup osx linux
---
#+end_html

*This documentation is now hosted at* [[http://digego.github.io/extempore/]]

**Update October 2015** building from source is now much easier
(assuming you're happy to use the GitHub master branch). Updated
instructions can now be found in the [[https://github.com/digego/extempore/blob/master/INSTALL.md][INSTALL.md]] file in the Extempore
source distribution.

* Ok, I've done that, so how do I start using Extempore?

The =extempore= executable on its own is cool, but things really start
to get interesting when you can interact with it by sending it xtlang
code to evaluate. So the next step is to [[file:2012-09-26-interacting-with-the-extempore-compiler.org][set up your text editor for
working with Extempore source code]].

It's probably worth [[file:2013-12-16-building-the-extempore-standard-library.org][building the standard library]] as well---it'll save
you heaps of time if you're restarting Extempore often.

After you're set up, then the next step is to learn about xtlang and
the Extempore runtime. The [[file:../extempore-docs/index.org][docs index]] has a complete list of all the
posts covering this stuff, and is probably the place to go next. Have
fun :)
