#+PROPERTY: header-args:extempore :tangle /tmp/2013-10-15-testing-topclock.xtm
#+begin_html
---
title: Testing TOPclock
alias: ["./2013-10-15-testing-topclock.html"]
tags: time
---
#+end_html

There's been a flurry of activity recently on the TOPLAP list about
the [[https://docs.google.com/document/d/19nTIibG_WoZaaK-GnQME70XcTH_il6I4Ckq93z3-98g/edit?pli%3D1][TOPLAP Clock Protocol]] (the protocol formerly known as TOPclock).
Basically, the idea is that when TOPLAPpers get together, they want to
be able to jam---and fiddling with sync issues isn't much fun.

To aid everyone in their implementation and testing of the protocol,
there's an Extempore TOPclock example/client in the current [[https://github.com/digego/extempore][Extempore
git master]], and also in the newly available [[file:2013-10-15-extempore-binary-beta-testers-wanted.org][Extempore binaries]].  

To run the TOPclock example file, =cd= into the =extempore= directory
(again, you can now get a pre-built Extempore on OSX and Linux---see
[[file:2013-10-15-extempore-binary-beta-testers-wanted.org][this post]] for instructions and caveats)

#+BEGIN_SRC sh
> cd extempore

# start Extempore, run the topclock example file
> ./extempore --run examples/core/topclock_metro.xtm
#+END_SRC

Extempore will start playing a metronome and also try and sync on the
local network via the TOPclock (A) protocol. Both the tempo and the
metre will change at regular intervals. If the TOPclock syncing is
working ok, then Extempore should stay in sync with any other devices
on the local network (including on localhost) which are similarly
using the TOPclock protocol to keep in sync.

Discussion about the details of the spec is ongoing, so don't take
this implementation to be gospel. But for those who are ploughing
ahead and implementing TOPclock support for their environments, it
might be helpful to have another client to test with.

If you have any issues, feel free to comment here or shoot them
through to the [[mailto:extemporelang@googlegroups.com][Extempore mailing list]].
